version: '3.8'

services:
  react-app:
    build:
      context: ../../
      dockerfile: ./docker-qa/Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    container_name: react-app
    # command: npm start
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - nt

  playwright-tests:
    build:
      context: ../
      dockerfile: ./docker-merchant/Dockerfile
    container_name: playwright-tests
    depends_on:
      react-app:
        condition: service_healthy
    environment:
      - REACT_APP_SERVER_URL=http://react-app:3000
    # command: npx playwright test ./tests
    networks:
      - nt

networks:
  nt:
    driver: bridge
