version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          CI: true
    steps:
      - checkout
      - setup_remote_docker

      # # Build  the Docker  image for Playwright tests
      # - run:
      #     name: Build Playwright tests Docker image
      #     command: docker build -t playwright-tests .

      # Use Docker-Compose to run the Playwright tests
      - run:
          name: Run Playwright tests
          command: echo "hellow this is pw frameworkd"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build 
